spring:
  application:
    name: mcp-profile-server
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        annotation-scanner:
          enabled: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
